spring:
  profiles:
    include:
      - datasource
      - actuator
      - shiro
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml